### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by mbagattini** [Wagnerp/Krypton-NET-5.460#1]
I'm getting an error while trying to install this package in a project targeting .NET Framework 4.6, here's the output:

`Could not install package 'KryptonToolkitSuite46 4.60.547'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

With other packages in projects targeting .NET 4.6.2 I have no problems, but for this project I can't upgrade the .NET Framework version.

**Comment by Wagnerp** [comment]
Hi @mbagattini,

Thank you for reporting this, I'm aware of this issue, but can't figure out how to fix it. If you want, I can publish the binaries on the releases tab?

**Comment by mbagattini** [comment]
Hi @Wagnerp ,
At the moment I'm directly referencing the assemblies from a local folder, so there's no need for you to prepare the binaries. I just wanted to move to the more manageable nuget references. Thank you anyway!

**Comment by Wagnerp** [comment]
Hi @mbagattini,

Thanks for replying, yes I know what you mean about moving to a more manageable format,  however how hard I've tried, I can't seem to get it working :(. Hopefully maybe sometime in the future.

**Comment by mbagattini** [comment]
Great! Thanks for the update!

**Comment by Wagnerp** [comment]
Hi @mbagattini 

You should now be able to download the `KryptonToolkitSuite5460` Nuget package. All updates in version 5.470 from February have been included.

The problem was that NuGet seems to hate it if you use the framework version number i.e `4.7` as your own version number.

**Comment by Wagnerp** [comment]
Hi @mbagattini 

Just to let you  know that I'm updating this repo, moreover, you can look at what the latest version is [here](https://github.com/Wagnerp/Krypton-NET-Version-Dashboard)
